"""
Hybrid LLM Provider - ExpenseFlowAI Hybrid AI Architecture

Orchestrates a Primary LLM Provider (Google Gemini 3.6 Flash) with a deterministic
Fallback Engine (Rule Engine + Template Store).

Guarantees 100% availability of personalized financial advisory and streaming responses:
1. Attempts generation via Gemini Provider.
2. If Gemini fails due to quota, timeout, network error, invalid API key, or service unavailability,
   automatically catches the exception, logs diagnostic details, and fails over to FallbackEngine.
"""

import logging
import time
import traceback
from typing import Optional, Dict, Any, List, AsyncGenerator

from app.ai.provider import LLMProvider
from app.ai.fallback_engine import FallbackEngine
from app.ai.gemini_provider import GeminiProvider

logger = logging.getLogger(__name__)


class HybridLLMProvider(LLMProvider):
    def __init__(
        self,
        primary_provider: Optional[LLMProvider] = None,
        fallback_provider: Optional[FallbackEngine] = None,
        **kwargs
    ):
        self.primary = primary_provider or GeminiProvider(**kwargs)
        self.fallback = fallback_provider or FallbackEngine()
        self.provider_name = f"hybrid({getattr(self.primary, 'provider_name', 'gemini')}+{self.fallback.provider_name})"
        self.model = getattr(self.primary, "model", "gemini-3.6-flash")

    def generate(
        self,
        prompt: str,
        system_prompt: Optional[str] = None,
        messages: Optional[List[Dict[str, str]]] = None,
        summary: Optional[Dict[str, Any]] = None,
        **kwargs
    ) -> str:
        """
        Generates text using Primary LLM (Gemini) with automatic failover to Fallback Engine.
        """
        logger.info("[HYBRID AI ENGINE] Requesting response from Primary AI Provider (%s)...", getattr(self.primary, 'provider_name', 'gemini'))
        start_time = time.perf_counter()

        try:
            response_text = self.primary.generate(
                prompt=prompt,
                system_prompt=system_prompt,
                messages=messages,
                summary=summary,
                **kwargs
            )
            elapsed = time.perf_counter() - start_time
            logger.info("[HYBRID AI ENGINE SUCCESS] Response generated by Primary AI Provider in %.2fs.", elapsed)
            return response_text

        except Exception as exc:
            elapsed = time.perf_counter() - start_time
            logger.warning(
                "[HYBRID AI ENGINE FALLBACK ACTIVATED] Primary AI Provider failed after %.2fs. Reason: %s (%s). Activating Fallback Rule Engine...",
                elapsed,
                type(exc).__name__,
                str(exc)
            )
            logger.debug("[Primary Provider Error Traceback]:\n%s", traceback.format_exc())

            return self.fallback.generate(
                prompt=prompt,
                system_prompt=system_prompt,
                messages=messages,
                summary=summary,
                **kwargs
            )

    async def generate_stream(
        self,
        prompt: str,
        system_prompt: Optional[str] = None,
        messages: Optional[List[Dict[str, str]]] = None,
        summary: Optional[Dict[str, Any]] = None,
        **kwargs
    ) -> AsyncGenerator[str, None]:
        """
        Streams response tokens from Primary LLM (Gemini) with automatic failover to Fallback Engine.
        """
        logger.info("[HYBRID AI ENGINE STREAM] Initiating stream with Primary AI Provider...")
        start_time = time.perf_counter()
        primary_failed = False
        tokens_emitted = False

        try:
            async for chunk in self.primary.generate_stream(
                prompt=prompt,
                system_prompt=system_prompt,
                messages=messages,
                summary=summary,
                **kwargs
            ):
                if "[Gemini API Error:" in chunk:
                    # Exception caught inside provider stream yield
                    logger.warning("[HYBRID AI ENGINE STREAM WARNING] Primary Provider returned stream error token: %s", chunk)
                    primary_failed = True
                    break
                tokens_emitted = True
                yield chunk

            if not primary_failed and tokens_emitted:
                elapsed = time.perf_counter() - start_time
                logger.info("[HYBRID AI ENGINE STREAM SUCCESS] Streaming completed via Primary AI Provider in %.2fs.", elapsed)
                return

        except Exception as exc:
            logger.warning(
                "[HYBRID AI ENGINE STREAM FALLBACK ACTIVATED] Primary Provider stream failed. Reason: %s (%s). Activating Fallback Stream...",
                type(exc).__name__,
                str(exc)
            )
            primary_failed = True

        if primary_failed or not tokens_emitted:
            logger.info("[HYBRID AI ENGINE STREAM FAILOVER] Executing Fallback Engine stream...")
            async for fb_chunk in self.fallback.generate_stream(
                prompt=prompt,
                system_prompt=system_prompt,
                messages=messages,
                summary=summary,
                **kwargs
            ):
                yield fb_chunk

    def health_check(self) -> Dict[str, Any]:
        """
        Returns combined health status of primary provider and fallback engine.
        """
        primary_health = self.primary.health_check()
        fallback_health = self.fallback.health_check()

        overall_status = "healthy" if primary_health.get("status") == "healthy" else "degraded"

        return {
            "provider": self.provider_name,
            "model": self.model,
            "status": overall_status,
            "primary": primary_health,
            "fallback": fallback_health
        }
