"""
Abstract LLM Provider Interface - ExpenseFlowAI

Defines the core contract for LLM integrations (Google Gemini 3.6 Flash, FallbackEngine, HybridProvider).
Ensures business logic and advisor components remain completely provider-agnostic.
"""

from abc import ABC, abstractmethod
from typing import Optional, Dict, Any, List, AsyncGenerator


class LLMProvider(ABC):
    @abstractmethod
    def generate(
        self,
        prompt: str,
        system_prompt: Optional[str] = None,
        messages: Optional[List[Dict[str, str]]] = None,
        summary: Optional[Dict[str, Any]] = None,
        **kwargs
    ) -> str:
        """
        Generates a complete, single text response for the given prompt.
        """
        pass

    @abstractmethod
    async def generate_stream(
        self,
        prompt: str,
        system_prompt: Optional[str] = None,
        messages: Optional[List[Dict[str, str]]] = None,
        summary: Optional[Dict[str, Any]] = None,
        **kwargs
    ) -> AsyncGenerator[str, None]:
        """
        Asynchronously streams token chunks as they are generated by the LLM.
        """
        pass

    @abstractmethod
    def health_check(self) -> Dict[str, Any]:
        """
        Checks connectivity and availability of the underlying LLM provider/model.
        """
        pass
