"""
Abstract LLM Provider Interface - ExpenseFlowAI

Defines the contract for LLM integrations (Ollama, local models, or future providers).
Ensures business logic and advisor components remain completely provider-agnostic.
"""

from abc import ABC, abstractmethod
from typing import Optional, Dict, Any, AsyncGenerator


class LLMProvider(ABC):
    @abstractmethod
    def generate(self, prompt: str, system_prompt: Optional[str] = None) -> str:
        """
        Generates a complete, single text response for the given prompt.
        """
        pass

    @abstractmethod
    async def generate_stream(
        self, prompt: str, system_prompt: Optional[str] = None
    ) -> AsyncGenerator[str, None]:
        """
        Asynchronously streams token chunks as they are generated by the LLM.
        """
        pass

    @abstractmethod
    def health_check(self) -> Dict[str, Any]:
        """
        Checks connectivity and availability of the underlying LLM provider/model.
        """
        pass
