"""
AI Financial Coach Service - ExpenseFlowAI Hybrid AI Architecture

Transforms raw FinanceEngine outputs into a structured, personalized financial
coaching assessment (JSON format) containing snapshots, strengths, risks,
actionable recommendations, next month focus areas, and positive reinforcement.

The AI NEVER performs financial arithmetic itself. All numbers are provided directly
by FinanceEngine and evaluated deterministically by InsightRuleEngine.
"""

import json
import logging
import re
from typing import Optional, Dict, Any, List
from sqlalchemy.orm import Session

from app.services.finance_engine import FinanceEngine
from app.ai.provider import LLMProvider
from app.ai.factory import get_llm_provider
from app.ai.insight_rules import InsightRuleEngine
from app.ai.templates import TemplateEngine
from app.ai.fallback_engine import FallbackEngine

logger = logging.getLogger(__name__)


COACH_SYSTEM_PROMPT = """You are ExpenseFlowAI Financial Coach, a compassionate, expert personal finance advisor.
You analyze verified user metrics generated by FinanceEngine and produce structured JSON coaching guidance.

RULES:
1. USE ONLY THE SUPPLIED FINANCIAL DATA: Do NOT invent or recalculate any balances or percentages.
2. OUTPUT STRICT JSON ONLY: You MUST respond with a single valid JSON object. No prose outside JSON.
3. STRUCTURED KEYS REQUIRED:
   - "summary": A 1-2 sentence executive summary of financial health.
   - "strengths": A list of 2-3 positive financial observations based on metrics.
   - "risks": A list of 1-3 identified financial risk factors or watch-outs.
   - "recommendations": A list of 3 prioritized, actionable advice steps.
   - "next_month_focus": A list of 2 focus points for the upcoming month.
   - "encouragement": A warm, encouraging closing statement.
"""


class AIFinancialCoachService:
    def __init__(self, provider: Optional[LLMProvider] = None):
        self.provider = provider or get_llm_provider()

    def generate_coaching_report(
        self,
        db: Session,
        user_id: int,
        period: str = "30d",
        focus_area: Optional[str] = None
    ) -> Dict[str, Any]:
        """
        Retrieves verified metrics from FinanceEngine, builds LLM prompt,
        executes provider generation, and parses/enforces structured JSON schema response.
        Falls back safely to InsightRuleEngine & TemplateEngine if LLM fails or returns invalid JSON.
        """
        summary = FinanceEngine.get_dashboard_summary(db, user_id=user_id, period=period)

        snapshot = {
            "income": summary.get("period_income", 0.0),
            "expenses": summary.get("period_expense", 0.0),
            "savings": summary.get("period_savings", 0.0),
            "savings_rate": summary.get("period_savings_rate", 0.0),
            "health_score": summary.get("health_score", 0),
            "health_status": summary.get("health_status", "N/A"),
            "reserve_months": summary.get("health_metrics", {}).get("reserve_months", 0.0),
            "budget_adherence_pct": summary.get("health_metrics", {}).get("budget_adherence_pct", 100.0),
            "bill_reliability_pct": summary.get("health_metrics", {}).get("bill_reliability_pct", 100.0),
        }

        # Build prompt including Rule Engine evaluated insights
        insights = InsightRuleEngine.evaluate_rules(summary)
        prompt = self._build_coach_prompt(summary, snapshot, insights, focus_area=focus_area)

        llm_response = ""
        try:
            llm_response = self.provider.generate(
                prompt=prompt,
                system_prompt=COACH_SYSTEM_PROMPT,
                summary=summary
            )
            parsed_json = self._extract_json(llm_response)
            if parsed_json:
                return {
                    "summary": str(parsed_json.get("summary", self._default_summary(summary, insights))),
                    "financial_snapshot": snapshot,
                    "strengths": self._ensure_list(parsed_json.get("strengths"), [i.details for i in insights if i.severity == "positive"]),
                    "risks": self._ensure_list(parsed_json.get("risks"), [i.details for i in insights if i.severity in ("warning", "critical")]),
                    "recommendations": self._ensure_list(parsed_json.get("recommendations"), self._default_recommendations(insights)),
                    "next_month_focus": self._ensure_list(parsed_json.get("next_month_focus"), self._default_focus()),
                    "encouragement": str(parsed_json.get("encouragement", "Consistency is key to wealth building. You are taking proactive control of your financial future!")),
                    "confidence": 0.95,
                }
        except Exception as exc:
            logger.warning("[AI Financial Coach] LLM generation/parsing failed (%s). Activating Fallback Rule Engine.", str(exc))

        # Deterministic Fallback if LLM unavailable or invalid JSON
        return self._build_deterministic_report(summary, insights)

    def _build_coach_prompt(
        self,
        summary: Dict[str, Any],
        snapshot: Dict[str, Any],
        insights: List[Any],
        focus_area: Optional[str] = None
    ) -> str:
        cat_spending = summary.get("category_spending", [])
        top_cats = ", ".join([f"{c['category']}: ${c['amount']:,.2f}" for c in cat_spending[:3]]) or "None recorded"
        insight_lines = [f"  - [{i.severity.upper()}] {i.title}: {i.details}" for i in insights]

        prompt = f"""
Financial Data Context (Source: FinanceEngine):
- Available Balance: ${summary.get('total_balance', 0.0):,.2f}
- Income ({summary.get('period', '30d')}): ${snapshot['income']:,.2f}
- Expenses ({summary.get('period', '30d')}): ${snapshot['expenses']:,.2f}
- Net Savings: ${snapshot['savings']:,.2f}
- Savings Rate: {snapshot['savings_rate']:.1f}%
- Health Score: {snapshot['health_score']}/100 ({snapshot['health_status']})
- Emergency Fund Reserve: {snapshot['reserve_months']:.1f} months
- Budget Adherence Rate: {snapshot['budget_adherence_pct']:.1f}%
- Bill Payment Reliability: {snapshot['bill_reliability_pct']:.1f}%
- Top Outflow Categories: {top_cats}

Evaluated Rule Engine Insights:
{chr(10).join(insight_lines)}
"""
        if focus_area:
            prompt += f"\nUser Requested Focus Area: {focus_area}\n"

        prompt += """
Generate JSON coaching object matching keys:
"summary", "strengths", "risks", "recommendations", "next_month_focus", "encouragement".
"""
        return prompt

    def _extract_json(self, text: str) -> Optional[Dict[str, Any]]:
        if not text:
            return None
        try:
            return json.loads(text)
        except json.JSONDecodeError:
            match = re.search(r"\{.*\}", text, re.DOTALL)
            if match:
                try:
                    return json.loads(match.group(0))
                except json.JSONDecodeError:
                    pass
        return None

    def _ensure_list(self, val: Any, default_list: List[str]) -> List[str]:
        if isinstance(val, list) and len(val) > 0:
            return [str(item) for item in val]
        return default_list

    def _build_deterministic_report(self, summary: Dict[str, Any], insights: List[Any]) -> Dict[str, Any]:
        return TemplateEngine.render_structured_coach(insights, summary)

    def _default_summary(self, summary: Dict[str, Any], insights: List[Any]) -> str:
        score = summary.get("health_score", 0)
        status = summary.get("health_status", "N/A")
        return f"Your overall financial health is rated as {status} with a composite score of {score}/100."

    def _default_recommendations(self, insights: List[Any]) -> List[str]:
        recs = [ins.details for ins in insights if ins.severity in ("warning", "critical")]
        if not recs:
            recs.append("Maintain current budget adherence and review monthly category spending trends.")
        return recs[:3]

    def _default_focus(self) -> List[str]:
        return [
            "Maintain 100% on-time bill payments to protect credit standing.",
            "Enforce category spending caps to optimize monthly net savings."
        ]


def get_ai_coach_service() -> AIFinancialCoachService:
    """
    Dependency provider for AIFinancialCoachService.
    Enables clean FastAPI dependency injection and unit test mocking.
    """
    return AIFinancialCoachService()
