"""
Predictive Cash Flow Engine Service - ExpenseFlowAI

Calculates 7-Day, 30-Day, and 90-Day balance projections based on historical run rates,
unpaid bills, budget commitments, and active goals retrieved from FinanceEngine.
The LLM NEVER performs financial math; it interprets mathematical projections into narrative guidance.
"""

from datetime import datetime, timedelta, timezone
import logging
from typing import Optional, Dict, Any, List
from sqlalchemy.orm import Session
from sqlalchemy import select

from app.services.finance_engine import FinanceEngine
from app.models.bill import Bill
from app.models.goal import Goal
from app.ai.provider import LLMProvider
from app.ai.factory import get_llm_provider

logger = logging.getLogger(__name__)


FORECAST_PROMPT_TEMPLATE = """You are ExpenseFlowAI Predictive Cash Flow Advisor.
Interpret the mathematical cashflow projections generated by FinanceEngine and explain the trajectory to the user.

FINANCIAL FORECAST DATA:
- Active Liquid Balance: ${total_balance:,.2f}
- 7-Day Expected Balance: ${b7:,.2f} (Net: ${n7:,.2f})
- 30-Day Expected Balance: ${b30:,.2f} (Net: ${n30:,.2f})
- 90-Day Expected Balance: ${b90:,.2f} (Net: ${n90:,.2f})
- Key Warnings: {warnings_str}
- Identified Opportunities: {opps_str}

RULES:
1. Explain WHY balances change over the 7, 30, and 90 day horizons.
2. Highlight upcoming liquidity risks or bill deadlines.
3. Recommend actionable steps to improve the cash flow trajectory.
4. Keep explanation clear, concise, and structured.
"""


class CashFlowForecastService:
    def __init__(self, provider: Optional[LLMProvider] = None):
        self.provider = provider or get_llm_provider()

    def generate_forecast(
        self,
        db: Session,
        user_id: int,
        period: str = "30d",
        include_ai_explanation: bool = True
    ) -> Dict[str, Any]:
        """
        Calculates mathematical balance projections for 7, 30, and 90 days out,
        compiles risk warnings & opportunities, and synthesizes narrative explanation.
        """
        # 1. Fetch verified financial metrics from FinanceEngine
        summary = FinanceEngine.get_dashboard_summary(db, user_id=user_id, period=period)
        total_balance = FinanceEngine.get_active_balance(db, user_id)

        period_income = float(summary.get("period_income", 0.0))
        period_expense = float(summary.get("period_expense", 0.0))

        # Determine daily run rates based on historical data (defaulting to 30 days window)
        days_window = 30.0 if period == "30d" else (90.0 if period == "90d" else 7.0)
        daily_income = max(period_income / days_window, 0.0)
        daily_expense = max(period_expense / days_window, 0.0)

        # 2. Fetch unpaid bills & active goals
        now = datetime.now(timezone.utc)
        stmt_bills = select(Bill).where(Bill.user_id == user_id, Bill.is_paid == False)
        unpaid_bills = db.execute(stmt_bills).scalars().all()

        stmt_goals = select(Goal).where(Goal.user_id == user_id)
        active_goals = db.execute(stmt_goals).scalars().all()

        # 3. Calculate 7-Day, 30-Day, and 90-Day Forecast Items
        forecast_items = []
        horizons = [(7, "7-Day"), (30, "30-Day"), (90, "90-Day")]

        all_warnings: List[str] = []
        all_opportunities: List[str] = []

        for days, label in horizons:
            cutoff = now + timedelta(days=days)
            
            # Sum bills due within horizon
            bills_due = [b for b in unpaid_bills if b.due_date and b.due_date.replace(tzinfo=timezone.utc) <= cutoff]
            bills_cost = sum(float(b.amount) for b in bills_due)

            proj_inc = round(daily_income * days, 2)
            proj_exp = round((daily_expense * days) + bills_cost, 2)
            net_change = round(proj_inc - proj_exp, 2)
            expected_bal = round(total_balance + net_change, 2)
            savings_proj = round(max(net_change, 0.0), 2)

            risk_events = []
            if bills_due:
                risk_events.append(f"{len(bills_due)} unpaid bill(s) due (${bills_cost:,.2f})")
            if net_change < 0:
                risk_events.append(f"Net cash deficit of ${abs(net_change):,.2f}")
            if expected_bal < 0:
                risk_events.append(f"CRITICAL: Account overdraft predicted (${expected_bal:,.2f})")

            forecast_items.append({
                "days": days,
                "period_label": label,
                "expected_balance": expected_bal,
                "projected_income": proj_inc,
                "projected_expenses": proj_exp,
                "net_change": net_change,
                "savings_projection": savings_proj,
                "risk_events": risk_events
            })

        # 4. Warnings and Opportunities Synthesis
        f7, f30, f90 = forecast_items[0], forecast_items[1], forecast_items[2]

        if f30["expected_balance"] < 0:
            all_warnings.append("High overdraft risk: 30-day projected balance falls below $0.")
        elif f30["net_change"] < 0:
            all_warnings.append(f"Negative 30-day cash flow trend (${f30['net_change']:,.2f}).")

        if len(unpaid_bills) > 0:
            all_warnings.append(f"{len(unpaid_bills)} pending bill(s) require upcoming payment.")

        if f30["net_change"] > 0:
            all_opportunities.append(f"Projected 30-day net surplus of ${f30['net_change']:,.2f} can be allocated to savings or debt payoff.")
        if active_goals:
            all_opportunities.append(f"{len(active_goals)} active goal(s) can benefit from automated surplus transfers.")
        if not all_opportunities:
            all_opportunities.append("Review recurring subscriptions to increase daily net savings margin.")

        # 5. Compute Confidence Score (0.0 to 1.0)
        confidence = 0.91
        if period_income == 0 and period_expense == 0:
            confidence = 0.70
        elif f30["expected_balance"] < 0:
            confidence = 0.85

        # 6. LLM Explanation Generation
        warnings_str = "; ".join(all_warnings) if all_warnings else "None"
        opps_str = "; ".join(all_opportunities) if all_opportunities else "None"

        prompt = FORECAST_PROMPT_TEMPLATE.format(
            total_balance=total_balance,
            b7=f7["expected_balance"], n7=f7["net_change"],
            b30=f30["expected_balance"], n30=f30["net_change"],
            b90=f90["expected_balance"], n90=f90["net_change"],
            warnings_str=warnings_str,
            opps_str=opps_str
        )

        if include_ai_explanation:
            try:
                explanation = self.provider.generate(prompt=prompt)
                if not explanation or len(explanation.strip()) < 10:
                    explanation = self._build_deterministic_explanation(total_balance, f30, all_warnings)
            except Exception as exc:
                logger.warning("LLM Cash Flow Forecast generation error (%s). Using fallback explanation.", str(exc))
                explanation = self._build_deterministic_explanation(total_balance, f30, all_warnings)
        else:
            explanation = self._build_deterministic_explanation(total_balance, f30, all_warnings)

        return {
            "forecast": forecast_items,
            "confidence": confidence,
            "warnings": all_warnings,
            "opportunities": all_opportunities,
            "explanation": explanation
        }

    def _build_deterministic_explanation(
        self,
        total_balance: float,
        f30: Dict[str, Any],
        warnings: List[str]
    ) -> str:
        trend = "positive" if f30["net_change"] >= 0 else "negative"
        warn_msg = f" Note: {warnings[0]}" if warnings else ""
        return (
            f"Based on historical run rates, your liquid balance is projected to move from "
            f"${total_balance:,.2f} to ${f30['expected_balance']:,.2f} over the next 30 days ({trend} net change of ${f30['net_change']:,.2f})."
            f"{warn_msg} Maintain disciplined category spending to optimize your 90-day cash reserve trajectory."
        )
