"""create_scenario_table

Revision ID: 38474c4b877e
Revises: 99037c27cbfe
Create Date: 2026-07-19 10:06:41.506929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38474c4b877e'
down_revision: Union[str, Sequence[str], None] = '99037c27cbfe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scenario',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('percent_change', sa.Float(), nullable=True),
    sa.Column('one_off_date', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scenario_category_id'), 'scenario', ['category_id'], unique=False)
    op.create_index(op.f('ix_scenario_id'), 'scenario', ['id'], unique=False)
    op.create_index(op.f('ix_scenario_user_id'), 'scenario', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scenario_user_id'), table_name='scenario')
    op.drop_index(op.f('ix_scenario_id'), table_name='scenario')
    op.drop_index(op.f('ix_scenario_category_id'), table_name='scenario')
    op.drop_table('scenario')
    # ### end Alembic commands ###
