"""create_financial_digest_table

Revision ID: 3c36782bc723
Revises: f99b28cf9158
Create Date: 2026-07-23 12:10:11.127829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c36782bc723'
down_revision: Union[str, Sequence[str], None] = 'f99b28cf9158'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('financial_digest',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('digest_type', sa.String(length=20), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('health_score', sa.Integer(), nullable=False),
    sa.Column('content_json', sa.Text(), nullable=False),
    sa.Column('pdf_path', sa.String(length=255), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_financial_digest_digest_type'), 'financial_digest', ['digest_type'], unique=False)
    op.create_index(op.f('ix_financial_digest_generated_at'), 'financial_digest', ['generated_at'], unique=False)
    op.create_index(op.f('ix_financial_digest_id'), 'financial_digest', ['id'], unique=False)
    op.create_index(op.f('ix_financial_digest_user_id'), 'financial_digest', ['user_id'], unique=False)
    op.create_index(op.f('ix_notification_category'), 'notification', ['category'], unique=False)
    op.create_index(op.f('ix_notification_created_at'), 'notification', ['created_at'], unique=False)
    op.create_index(op.f('ix_notification_is_read'), 'notification', ['is_read'], unique=False)
    op.create_index(op.f('ix_notification_priority'), 'notification', ['priority'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notification_priority'), table_name='notification')
    op.drop_index(op.f('ix_notification_is_read'), table_name='notification')
    op.drop_index(op.f('ix_notification_created_at'), table_name='notification')
    op.drop_index(op.f('ix_notification_category'), table_name='notification')
    op.drop_index(op.f('ix_financial_digest_user_id'), table_name='financial_digest')
    op.drop_index(op.f('ix_financial_digest_id'), table_name='financial_digest')
    op.drop_index(op.f('ix_financial_digest_generated_at'), table_name='financial_digest')
    op.drop_index(op.f('ix_financial_digest_digest_type'), table_name='financial_digest')
    op.drop_table('financial_digest')
    # ### end Alembic commands ###
