"""create_ai_explanation_table

Revision ID: a34d3994b1a1
Revises: 3c36782bc723
Create Date: 2026-07-23 12:22:45.849836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a34d3994b1a1'
down_revision: Union[str, Sequence[str], None] = '3c36782bc723'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_explanation',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('feature', sa.String(length=50), nullable=False),
    sa.Column('target_id', sa.String(length=100), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('data_used_json', sa.Text(), nullable=False),
    sa.Column('metrics_json', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('assumptions_json', sa.Text(), nullable=False),
    sa.Column('limitations_json', sa.Text(), nullable=False),
    sa.Column('actions_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_explanation_created_at'), 'ai_explanation', ['created_at'], unique=False)
    op.create_index(op.f('ix_ai_explanation_feature'), 'ai_explanation', ['feature'], unique=False)
    op.create_index(op.f('ix_ai_explanation_id'), 'ai_explanation', ['id'], unique=False)
    op.create_index(op.f('ix_ai_explanation_target_id'), 'ai_explanation', ['target_id'], unique=False)
    op.create_index(op.f('ix_ai_explanation_user_id'), 'ai_explanation', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_explanation_user_id'), table_name='ai_explanation')
    op.drop_index(op.f('ix_ai_explanation_target_id'), table_name='ai_explanation')
    op.drop_index(op.f('ix_ai_explanation_id'), table_name='ai_explanation')
    op.drop_index(op.f('ix_ai_explanation_feature'), table_name='ai_explanation')
    op.drop_index(op.f('ix_ai_explanation_created_at'), table_name='ai_explanation')
    op.drop_table('ai_explanation')
    # ### end Alembic commands ###
