"""create_intelligence_tables

Revision ID: b51e7f158ffa
Revises: 1c1cdbeccb9d
Create Date: 2026-07-18 19:54:41.538214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b51e7f158ffa'
down_revision: Union[str, Sequence[str], None] = '1c1cdbeccb9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_briefing',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_briefing_date'), 'daily_briefing', ['date'], unique=False)
    op.create_index(op.f('ix_daily_briefing_id'), 'daily_briefing', ['id'], unique=False)
    op.create_index(op.f('ix_daily_briefing_user_id'), 'daily_briefing', ['user_id'], unique=False)
    op.create_table('financial_event',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('event_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_dismissed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_financial_event_id'), 'financial_event', ['id'], unique=False)
    op.create_index(op.f('ix_financial_event_user_id'), 'financial_event', ['user_id'], unique=False)
    op.create_table('financial_insight',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_financial_insight_id'), 'financial_insight', ['id'], unique=False)
    op.create_index(op.f('ix_financial_insight_user_id'), 'financial_insight', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_financial_insight_user_id'), table_name='financial_insight')
    op.drop_index(op.f('ix_financial_insight_id'), table_name='financial_insight')
    op.drop_table('financial_insight')
    op.drop_index(op.f('ix_financial_event_user_id'), table_name='financial_event')
    op.drop_index(op.f('ix_financial_event_id'), table_name='financial_event')
    op.drop_table('financial_event')
    op.drop_index(op.f('ix_daily_briefing_user_id'), table_name='daily_briefing')
    op.drop_index(op.f('ix_daily_briefing_id'), table_name='daily_briefing')
    op.drop_index(op.f('ix_daily_briefing_date'), table_name='daily_briefing')
    op.drop_table('daily_briefing')
    # ### end Alembic commands ###
