"""create_personalization_and_behavior_tables

Revision ID: deb43d1f520c
Revises: 10f86d5f587c
Create Date: 2026-07-23 11:12:32.495947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'deb43d1f520c'
down_revision: Union[str, Sequence[str], None] = '10f86d5f587c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_memories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_memories_category'), 'ai_memories', ['category'], unique=False)
    op.create_index(op.f('ix_ai_memories_id'), 'ai_memories', ['id'], unique=False)
    op.create_index(op.f('ix_ai_memories_key'), 'ai_memories', ['key'], unique=False)
    op.create_index(op.f('ix_ai_memories_user_id'), 'ai_memories', ['user_id'], unique=False)
    op.create_index('ix_user_memory_category_key', 'ai_memories', ['user_id', 'category', 'key'], unique=False)
    op.create_table('ai_personalization_settings',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('enable_ai_personalization', sa.Boolean(), nullable=False),
    sa.Column('enable_ai_learning', sa.Boolean(), nullable=False),
    sa.Column('coaching_style', sa.String(length=50), nullable=False),
    sa.Column('recommendation_frequency', sa.String(length=50), nullable=False),
    sa.Column('response_detail', sa.String(length=50), nullable=False),
    sa.Column('enable_smart_suggestions', sa.Boolean(), nullable=False),
    sa.Column('enable_goal_recommendations', sa.Boolean(), nullable=False),
    sa.Column('enable_spending_insights', sa.Boolean(), nullable=False),
    sa.Column('enable_memory', sa.Boolean(), nullable=False),
    sa.Column('enable_behavior_tracking', sa.Boolean(), nullable=False),
    sa.Column('enable_goal_tracking', sa.Boolean(), nullable=False),
    sa.Column('enable_communication_preference_learning', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_personalization_settings_id'), 'ai_personalization_settings', ['id'], unique=False)
    op.create_index(op.f('ix_ai_personalization_settings_user_id'), 'ai_personalization_settings', ['user_id'], unique=True)
    op.create_table('user_behavior_event',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_behavior_event_id'), 'user_behavior_event', ['id'], unique=False)
    op.create_index(op.f('ix_user_behavior_event_user_id'), 'user_behavior_event', ['user_id'], unique=False)
    op.create_table('user_learned_behavior',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('observation', sa.String(length=255), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_learned_behavior_id'), 'user_learned_behavior', ['id'], unique=False)
    op.create_index(op.f('ix_user_learned_behavior_user_id'), 'user_learned_behavior', ['user_id'], unique=False)
    op.create_table('user_preferences',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('communication_style', sa.String(length=50), nullable=False),
    sa.Column('category_sensitivities', sa.Text(), nullable=True),
    sa.Column('ignored_recommendation_types', sa.Text(), nullable=True),
    sa.Column('auto_reminder_lead_days', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_preferences_id'), 'user_preferences', ['id'], unique=False)
    op.create_index(op.f('ix_user_preferences_user_id'), 'user_preferences', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_preferences_user_id'), table_name='user_preferences')
    op.drop_index(op.f('ix_user_preferences_id'), table_name='user_preferences')
    op.drop_table('user_preferences')
    op.drop_index(op.f('ix_user_learned_behavior_user_id'), table_name='user_learned_behavior')
    op.drop_index(op.f('ix_user_learned_behavior_id'), table_name='user_learned_behavior')
    op.drop_table('user_learned_behavior')
    op.drop_index(op.f('ix_user_behavior_event_user_id'), table_name='user_behavior_event')
    op.drop_index(op.f('ix_user_behavior_event_id'), table_name='user_behavior_event')
    op.drop_table('user_behavior_event')
    op.drop_index(op.f('ix_ai_personalization_settings_user_id'), table_name='ai_personalization_settings')
    op.drop_index(op.f('ix_ai_personalization_settings_id'), table_name='ai_personalization_settings')
    op.drop_table('ai_personalization_settings')
    op.drop_index('ix_user_memory_category_key', table_name='ai_memories')
    op.drop_index(op.f('ix_ai_memories_user_id'), table_name='ai_memories')
    op.drop_index(op.f('ix_ai_memories_key'), table_name='ai_memories')
    op.drop_index(op.f('ix_ai_memories_id'), table_name='ai_memories')
    op.drop_index(op.f('ix_ai_memories_category'), table_name='ai_memories')
    op.drop_table('ai_memories')
    # ### end Alembic commands ###
